{
    "Message": "Download in progress...",
    "CompletionMessage": "Download Successful",
    "CompletionTimeout": 7,
    "OnSuccess": "/ZSAPAssetManager/Actions/DEST_SAM2505_PPROP/Service/DownloadOffline.action",
    "_Type": "Action.Type.ProgressBanner"
}