{
    "_Type": "Action.Type.OpenBarcodeScanner",
    "OnSuccess": "/SAPAssetManager/Rules/Cooperation/CooperationQRCodeScanSuccess.js",
    "OnFailure": "/SAPAssetManager/Actions/Cooperation/CooperationQRCodeScanFailed.action",
    "ActionResult": {
        "_Name": "BarcodeScanner"
    }
}